/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: MaX3Dd (https://sketchfab.com/MaX3Dd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/farm-house-ee792a21ec6744d9a5488118b1a88750
Title: Farm House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/LaAntonia/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={49.786}>
        <mesh geometry={nodes.house_Farm_house_D_0.geometry} material={materials.Farm_house_D} />
        <mesh geometry={nodes.house_House_Side_D_0.geometry} material={materials.House_Side_D} />
        <mesh geometry={nodes.house_Roof_D_0.geometry} material={materials.Roof_D} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
